---
title: "Schematic codes for Main Tables and Figures"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```


```{r,message=FALSE,warning=FALSE,include=FALSE}
library(clubSandwich)
library(parameters)
library(sjstats)
library(rms)
library(survminer)
library(survival)
library(broom)
library("data.table")   
library(gtsummary)
library(gt)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(sandwich)
library(boot)
library(table1)
library(flextable)
library(plyr)
library(Rcpp)
library(modelr)
library(readr)
library(gWQS)
library(broom.mixed)
library(yaml)
library(rmarkdown)
library(officer)
library(scales)
library(spatstat)
library(survey)
library(devtools)
library(cobalt)
# install_version("optmatch", version = "0.9.17", repos = "http://cran.us.r-project.org")
# install_github("markmfredrickson/RItools")
library(RItools)
library(optmatch)
library(mice)
library(rstan)
library('ggplot2')
# install.packages("remotes")
# remotes::install_github("ElenaColicino/bwqs")
library(BWQS)
library('mvtnorm')
library(readxl)
library(writexl)
library(spatstat)
#-------------------------------------------------------import data set
whole_cohort<-  read_excel("~/Projects/S-PRESTO/input/fertility/spresto_data_20230104.xlsx", sheet="Data")


#-------------------------------------------------------change variable format
### whether in the analysis sample:participate in blood measurement and have record for pregnant ###
whole_cohort$include<- ifelse(whole_cohort$participation == 1 & is.na(whole_cohort$ttp_pregnant_ref) == FALSE, 1, 0)


### demographic factors ### 
#### Analysis Batch
whole_cohort$Analysis_Batch_recat<- factor(whole_cohort$Analysis_Batch_recat,
                                     levels = c("B6","B2","B3","B4","B5"))


#### ethnicity categorization
whole_cohort$ethnicity_specified_recat<- factor(whole_cohort$ethnicity_specified_recat,
                                           levels=c("Chinese","Malay","Indian"))
#### highest education                            
whole_cohort$pcv1_highest_education_completed_recat<- factor(whole_cohort$pcv1_highest_education_completed_recat,
                                           levels=c("University","Primary/Secondary/Post_secondary"))
#### parity status
whole_cohort$pcv1_parity_recat<- factor(whole_cohort$pcv1_parity_recat,
                                  levels=c("0",">= 1"))

#### smoking status
whole_cohort$pcv1_smoker<- factor(whole_cohort$pcv1_smoker,
                                  levels = c(0:2),
                                  labels = c("Never smoke", "Smoker", "Ex-smoker")) 


label(whole_cohort$Analysis_Batch_recat)<- "Analysis Batch"
label(whole_cohort$ttp_pregnant_ref)<- "Pregnant"
label(whole_cohort$live_birth_recat)<- "Live birth"
label(whole_cohort$ttp_in_cycle1)<- "Time to pregnant (in menstrual cycle)"
label(whole_cohort$age_at_recruitment)<- "Age at Recruitment (year)"
label(whole_cohort$ethnicity_specified_recat)<- "Ethnicity"
label(whole_cohort$pcv1_highest_education_completed_recat)<- "Highest Education Completed at preconception one visit"
label(whole_cohort$pcv1_parity_recat)<- "History of parity"
label(whole_cohort$pcv1_bmi)<- "BMI at Preconception (kg/m2)"
label(whole_cohort$pcv1_smoker)<- "Smoking status"
label(whole_cohort$PFHxS)<- "Log2(PFHxS(ng/ml))"
label(whole_cohort$PFHpA_bi_num)<- "PFHpA (LOD)"
label(whole_cohort$PFDA_bi_num)<- "PFDA (LOD)"
label(whole_cohort$PFHpS_bi_num)<- "PFHpS (LOD)"
label(whole_cohort$PFOS_Total)<- "Log2(PFOS_Total(ng/ml))"
label(whole_cohort$PFOA_Linear)<- "Log2(PFOA_Linear(ng/ml))"
label(whole_cohort$PFNA)<- "Log2(PFNA(ng/ml))"
label(whole_cohort$PFHxS_quar_num)<- "Quartile PFHxS"
label(whole_cohort$PFHpA_quar_num)<- "Quartile PFHpA"
label(whole_cohort$PFDA_quar_num)<- "Quartile PFDA"
label(whole_cohort$PFHpS_quar_num)<- "Quartile PFHpS"
label(whole_cohort$PFOS_Total_quar_num)<- "Quartile PFOS_Total"
label(whole_cohort$PFOA_Linear_quar_num)<- "Quartile PFOA_Linear"
label(whole_cohort$PFNA_quar_num)<- "Quartile PFNA"


#-------------------------------------------------------2. only include blood sample
blood<- whole_cohort %>% 
        filter(participation==1 & is.na(ttp_pregnant_ref)==FALSE)


```


# Table 1
```{r,message=FALSE,warning=FALSE}
demo_table <- blood %>%
    select(ttp_pregnant_ref, age_at_recruitment,pcv1_bmi, pcv1_highest_education_completed_recat,ethnicity_specified_recat, pcv1_parity_recat, pcv1_smoker, PFHxS, PFHpA,
           PFOS_Total, PFOA_Linear, PFNA, PFDA, PFHpS, ttp_in_cycle1) %>%
    tbl_summary(type = list(c("PFHxS", "PFHpA", "PFOS_Total", "PFOA_Linear", "PFNA","PFDA", "PFHpS", "ttp_in_cycle1") ~ "continuous"), 
                by = ttp_pregnant_ref,
                missing_text = "Missing", 
                digits = everything() ~ 2
                ) %>%
    bold_labels() %>%
    add_p(test = list(all_categorical() ~ "chisq.test",
          pcv1_smoker ~ "fisher.test"),
          pvalue_fun = function(x) style_pvalue(x, digits = 3)) %>%
    bold_p() %>%
    add_overall()

demo_table

```


# Table 2
```{r,warning=FALSE,message=FALSE}
### calculate ipw for sampling bias ###

#  remove missing values for sampling bias model
keeplist1=c("participation",'age_at_recruitment', 'pcv1_highest_education_completed_recat','ethnicity_specified_recat','pcv1_parity_recat')
whole_cohort_keep<- whole_cohort[,keeplist1]
whole_cohort_keep1<- whole_cohort[complete.cases(whole_cohort_keep),c(keeplist1, "ttp_pregnant_ref")]

# a. estimation of probability that the individual had blood measurement
ipw_part_sb_nomiss1 <- glm(participation ~ age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat, 
           family = binomial, data = whole_cohort_keep1)
pd_sb_nomiss<-  predict(ipw_part_sb_nomiss1, type = "response")

# b. estimation of numerator of ip weights
ipw_part_sb_nomiss2 <- glm(participation ~ 1,
           family = binomial, data = whole_cohort_keep1)
pn_sb_nomiss<-  predict(ipw_part_sb_nomiss2, type = "response")

# c. stabilized inverse of probability
whole_cohort_keep1$ipw_sb_nomiss <- ifelse(whole_cohort_keep1$participation == 0, ((1-pn_sb_nomiss)/(1-pd_sb_nomiss)),
                    (pn_sb_nomiss/pd_sb_nomiss))


blood$ipw_sb_nomiss<- (whole_cohort_keep1 %>% filter(participation==1 & is.na(ttp_pregnant_ref)==FALSE))$ipw_sb_nomiss
summary(blood$ipw_sb_nomiss)
```

## TTP - observed cycles (time to event outcome)
### Individual PFAS 
```{r,warning=FALSE,message=FALSE}
blood_ttpnomiss<- blood %>% 
                  filter(is.na(ttp_in_cycle1)==FALSE & is.na(status)==FALSE)

### model fit
surv_model_adjusted1<- coxph(Surv(ttp_in_cycle1,status) ~ PFHxS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted2<- coxph(Surv(ttp_in_cycle1,status) ~ PFHpA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted3<- coxph(Surv(ttp_in_cycle1,status) ~ PFOS_Total_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted4<- coxph(Surv(ttp_in_cycle1,status) ~ PFOA_Linear_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted5<- coxph(Surv(ttp_in_cycle1,status) ~ PFNA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted6<- coxph(Surv(ttp_in_cycle1,status) ~ PFDA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

surv_model_adjusted7<- coxph(Surv(ttp_in_cycle1,status) ~ PFHpS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,
                         blood_ttpnomiss, weights= blood_ttpnomiss$ipw_sb_nomiss,robust=TRUE) 

 
### test proportional hazard assumption
test_ph_assum1<- cox.zph(surv_model_adjusted1)
test_ph_assum2<- cox.zph(surv_model_adjusted2)
test_ph_assum3<- cox.zph(surv_model_adjusted3)
test_ph_assum4<- cox.zph(surv_model_adjusted4)
test_ph_assum5<- cox.zph(surv_model_adjusted5)
test_ph_assum6<- cox.zph(surv_model_adjusted6)
test_ph_assum7<- cox.zph(surv_model_adjusted7)

test_ph_assum1
test_ph_assum2
test_ph_assum3
test_ph_assum4
test_ph_assum5
test_ph_assum6
test_ph_assum7

### summarize models into table
surv_model_adjusted1_table<- surv_model_adjusted1 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFHxS_quar_num,
                               show_single_row=PFHxS_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted2_table<- surv_model_adjusted2 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFHpA_quar_num,
                               show_single_row=PFHpA_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted3_table<- surv_model_adjusted3 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFOS_Total_quar_num,
                               show_single_row=PFOS_Total_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted4_table<- surv_model_adjusted4 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFOA_Linear_quar_num,
                               show_single_row=PFOA_Linear_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted5_table<- surv_model_adjusted5 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFNA_quar_num,
                               show_single_row=PFNA_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted6_table<- surv_model_adjusted6 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFDA_quar_num,
                               show_single_row=PFDA_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 

surv_model_adjusted7_table<- surv_model_adjusted7 %>%
                               tbl_regression(exponentiate = TRUE,
                               include = PFHpS_quar_num,
                               show_single_row=PFHpS_quar_num,
                               pvalue_fun = function(x) style_pvalue(x, digits = 3),
                               estimate_fun = function(x) style_sigfig(x, digits = 3)) 
### combine tables
surv_model_adjusted_table<- tbl_stack(tbls = list(surv_model_adjusted1_table,surv_model_adjusted2_table,surv_model_adjusted3_table,surv_model_adjusted4_table,surv_model_adjusted5_table,surv_model_adjusted6_table,surv_model_adjusted7_table))%>%
                               modify_header(
                                   update = list(
                                   label ~ '**PFAS Variable**',
                                   estimate ~ '**FR**'))%>%
                               bold_p() %>%
                               bold_labels()%>% 
                               as_gt()%>% 
                                  tab_footnote(
                                    footnote=c("Adjusted model: adjusted for Batch effect, age at recruitment, Highest education status, ethinicity, and parity at pcv1 visit"),
                                    locations=  cells_stubhead()
                         )

surv_model_adjusted_table

```

### Joint effect of PFAS - BWQS
```{r, message=FALSE,warning=FALSE}
#################################
#BWQS survival analysis with IPW#
#################################

bwqs_survival_code <- "data {
    int<lower=1> N_uncensored;    //number of individual                               
    int<lower=1> N_censored;                                        
                       
    vector<lower=0>[N_censored] times_censored;                          
    vector<lower=0>[N_uncensored] times_uncensored;              
    
    int<lower=0> C1;                                // number of element of first mix
    matrix[N_censored,C1] X_censored_C1;            // matrix of first mix censored
    matrix[N_uncensored,C1] X_uncensored_C1;        // matrix of first mix uncensored


    int<lower=0> NC;                               // covariates                                             
    matrix[N_censored,NC] X_censored_NC;                               
    matrix[N_uncensored,NC] X_uncensored_NC;       

    vector[C1] DalpC1;                            // vector of the Dirichlet coefficients for first mix
    
    vector[N_uncensored] sw_uncensored;            // IPW type of weights for uncensored

    vector[N_censored] sw_censored;            // IPW type of weights for censored

}

parameters {
    real mu;                    // intercepts
    real beta;                  // mixture effect
    real <lower=0> sigma;
    vector[NC] delta;           // covariates coefficients
    simplex[C1] WC1;            // weights of first mix
}

transformed parameters {

    vector[N_censored] Xb_censored;
    vector[N_uncensored] Xb_uncensored;
    Xb_censored = mu + (X_censored_C1*WC1)*beta  + X_censored_NC*delta;
    Xb_uncensored = mu + (X_uncensored_C1*WC1)*beta  + X_uncensored_NC*delta;

}
model {

    mu ~ normal(0, 10);
    sigma ~ inv_gamma(0.01,0.01);
    beta ~ normal(0, sigma);
    for(j in 1:NC) delta[j] ~ normal(0,10);
    WC1 ~ dirichlet(DalpC1);
    for(n1 in 1:N_uncensored){
        target += exponential_lpdf(times_uncensored[n1] | exp(Xb_uncensored[n1]))* sw_uncensored[n1]; 
    }
    for(n2 in 1:N_censored){
        target += exponential_lccdf(times_censored[n2] | exp(Xb_censored[n2]))* sw_censored[n2]; 
    }
        }

"



bwqs_survival_sm <- rstan::stan_model(model_code =  bwqs_survival_code)

# Read the data
spresto<- blood_ttpnomiss %>% 
  select(ttp_in_cycle1,status,PFHxS_quar_num,PFHpA_quar_num,PFOS_Total_quar_num,PFOA_Linear_quar_num,PFNA_quar_num,PFDA_quar_num,PFHpS_quar_num,Analysis_Batch_recat,age_at_recruitment, pcv1_highest_education_completed_recat,ethnicity_specified_recat,pcv1_parity_recat, ipw_sb_nomiss)


sapply(spresto, function(x) sum(is.na(x))) 

spresto <- na.omit(spresto)
spresto <- DataExplorer::dummify(spresto)

# subset the data
spresto <- as.data.frame(spresto[,c("ttp_in_cycle1","status",'PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num',
                                    "Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
                                    "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
                                    "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1","ipw_sb_nomiss")])


# List of PFAS
mix_name_1 <- c('PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num' )

# List of covariates
KV_name <- c("Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
             "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
             "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1")


data_reg <- list(
  N_uncensored = as.numeric(table(spresto$status))[2],
  N_censored = as.numeric(table(spresto$status))[1],
  
  times_censored =  spresto$ttp_in_cycle1[spresto$status == 0],
  times_uncensored =  spresto$ttp_in_cycle1[spresto$status == 1],
  
  C1 = length(PFAS_name),
  X_censored_C1 = as.matrix(spresto[spresto$status == 0, mix_name_1]),
  X_uncensored_C1 = as.matrix(spresto[spresto$status == 1, mix_name_1]),
  
  NC = length(KV_name),                                                                            
  X_censored_NC = as.matrix(spresto[spresto$status == 0, KV_name]),
  X_uncensored_NC = as.matrix(spresto[spresto$status == 1, KV_name]),   
  
  sw_censored = spresto$ipw_sb_nomiss[spresto$status == 0],
  sw_uncensored = spresto$ipw_sb_nomiss[spresto$status == 1],
  
  DalpC1 = rep(1, 7)
)

fit_bwqs_survival_sm <- rstan::sampling(bwqs_survival_sm,
                                        data = data_reg,
                                        chains = 2,
                                        iter = 1e4,
                                        thin = 1,
                                        refresh = 0, verbose = F,
                                        control=list(max_treedepth = 20,
                                                     adapt_delta = 0.999999999999999))


sum_fit_bwqs_survival_sm <- round(summary(fit_bwqs_survival_sm,
                                          probs = c(0.025, 0.975))$summary,4)


# summarize results
estimate<- round(c(exp(sum_fit_bwqs_survival_sm['beta','mean']), exp(sum_fit_bwqs_survival_sm['beta','2.5%']), exp(sum_fit_bwqs_survival_sm['beta','97.5%'])), 3)

estimate

PFAS_name<- c('PFHxS', 'PFHpA', 'PFOS_Total', 'PFOA_Linear', 'PFNA', 'PFDA', 'PFHpS')
weights<- as.numeric(sum_fit_bwqs_survival_sm[c('WC1[1]','WC1[2]','WC1[3]','WC1[4]','WC1[5]','WC1[6]','WC1[7]'),'mean'])
PFAS_weights<- data.frame(PFAS_name, weights) %>% 
               arrange( desc(weights))
PFAS_weights

```



## Pregnant
### Individual PFAS
```{r, message=FALSE,warning=FALSE}

## fit the model
PFAS_preg_adjusted_bm_1_matched_reg2<- glm(ttp_pregnant_ref ~ PFHxS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family=binomial(), weights = blood$ipw_sb_nomiss) 


PFAS_preg_adjusted_bm_2_matched_reg2<- glm(ttp_pregnant_ref ~PFHpA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_preg_adjusted_bm_3_matched_reg2<- glm(ttp_pregnant_ref ~PFOS_Total_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_preg_adjusted_bm_4_matched_reg2<- glm(ttp_pregnant_ref ~PFOA_Linear_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_preg_adjusted_bm_5_matched_reg2<- glm(ttp_pregnant_ref ~PFNA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_preg_adjusted_bm_6_matched_reg2<- glm(ttp_pregnant_ref ~PFDA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_preg_adjusted_bm_7_matched_reg2<- glm(ttp_pregnant_ref ~PFHpS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

## extract the information from the model
PFAS_preg_adjusted_bm_1_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_1_matched_reg2, ci_method="wald",vcov = "HC3" ,exponentiate = TRUE
))

PFAS_preg_adjusted_bm_2_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_2_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_preg_adjusted_bm_3_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_3_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_preg_adjusted_bm_4_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_4_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_preg_adjusted_bm_5_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_5_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_preg_adjusted_bm_6_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_6_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_preg_adjusted_bm_7_matched_robust_reg2<- as_tibble(model_parameters(PFAS_preg_adjusted_bm_7_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))



PFAS_preg_adjusted_bm_matched_robust_reg2_estimate<- rbind(PFAS_preg_adjusted_bm_1_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_2_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_3_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_4_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_5_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_6_matched_robust_reg2[2,2],
                                                    PFAS_preg_adjusted_bm_7_matched_robust_reg2[2,2])

PFAS_preg_adjusted_bm_matched_robust_reg2_sd<-rbind(PFAS_preg_adjusted_bm_1_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_2_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_3_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_4_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_5_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_6_matched_robust_reg2[2,3],
                                                    PFAS_preg_adjusted_bm_7_matched_robust_reg2[2,3])

PFAS_preg_adjusted_bm_matched_robust_reg2_ci_low<-rbind(PFAS_preg_adjusted_bm_1_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_2_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_3_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_4_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_5_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_6_matched_robust_reg2[2,5],
                                                    PFAS_preg_adjusted_bm_7_matched_robust_reg2[2,5])

PFAS_preg_adjusted_bm_matched_robust_reg2_ci_high<-rbind(PFAS_preg_adjusted_bm_1_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_2_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_3_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_4_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_5_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_6_matched_robust_reg2[2,6],
                                                    PFAS_preg_adjusted_bm_7_matched_robust_reg2[2,6])

PFAS_preg_adjusted_bm_matched_robust_reg2_p<-rbind(PFAS_preg_adjusted_bm_1_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_2_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_3_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_4_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_5_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_6_matched_robust_reg2[2,9],
                                                    PFAS_preg_adjusted_bm_7_matched_robust_reg2[2,9])

PFAS_name<- c("PFHxS","PFHpA","PFOS_Total","PFOA_Linear","PFNA","PFDA","PFHpS")



## put all infomation in the table
PFAS_preg_adjusted_bm_matched_robust_reg2<- data.frame(PFAS_name,
           round(PFAS_preg_adjusted_bm_matched_robust_reg2_estimate,3),
           round(PFAS_preg_adjusted_bm_matched_robust_reg2_ci_low,3),
           round(PFAS_preg_adjusted_bm_matched_robust_reg2_ci_high,3),
           round(PFAS_preg_adjusted_bm_matched_robust_reg2_p,4))%>% 
unite(ci,CI_low,CI_high,sep=",")


PFAS_preg_adjusted_bm_matched_robust_reg2_table1<- flextable(PFAS_preg_adjusted_bm_matched_robust_reg2)  %>% 
                 set_header_labels(Coefficient="OR",ci="95% CI",p="p.value") %>% 
                 add_footer_lines(values=c("p.value less than 0.05 is marked in red","Adjusted model: adjusted for Batch effect, age at recruitment, Highest education status, ethinicity, and parity at pcv1 visit"))%>% 
                 color( ~p<0.05,~p,color="red") %>% 
                 theme_box 


PFAS_preg_adjusted_bm_matched_robust_reg2_table1


```


### Joint effect of PFAS - BWQS
```{r, message=FALSE,warning=FALSE}

###############################
#BWQS logit regression with IPW
###############################

model_bwqs_stan_w = "data {

int<lower=0> N;          // number of individual
int<lower=0> C;          // number of chemicals
int<lower=0> K;          // number of covariates
matrix[N,C] X;                         // matrix of indipendent variable
matrix[N,K] KV;                       // matrix of covariates
vector[C] Dalp;          // vector of the Dirichlet coefficients
vector[N] sw;            // IPW type of weights
int<lower=0, upper=1> y[N];  // outcome binomial variable
}
parameters {
real beta0;              // intercepts
real beta1;              // overall effect
vector[K] delta;         // covariates coefficients
simplex[C] W;            // weights for contribution of each exposure in the mixture
}
transformed parameters {
vector[N] Xb;
Xb = beta0 + beta1*(X*W) + KV*delta;
}
model {
beta0 ~ normal(0, 100);
beta1 ~ normal(0, 100);
delta ~ normal(0, 100);
W ~ dirichlet(Dalp);
for(n in 1:N){
 target += bernoulli_logit_lpmf(y[n] | Xb[n]) * sw[n];
}


}
generated quantities {
vector[N] log_lik;
for (nn in 1:N)
log_lik[nn] = bernoulli_logit_lpmf(y[nn] | Xb[nn]);
}
"


# Read the data
spresto<- blood %>% 
  select(ttp_pregnant_ref,live_birth_recat,PFHxS_quar_num,PFHpA_quar_num,PFOS_Total_quar_num,PFOA_Linear_quar_num,PFNA_quar_num,PFDA_quar_num,PFHpS_quar_num,Analysis_Batch_recat,age_at_recruitment, pcv1_highest_education_completed_recat,ethnicity_specified_recat,pcv1_parity_recat, ipw_sb_nomiss)

spresto <- na.omit(spresto)
spresto <- DataExplorer::dummify(spresto)

# subset the data
spresto <- as.data.frame(spresto[,c('PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num',
                                    "Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
                                    "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
                                    "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1",
                                   "ipw_sb_nomiss","ttp_pregnant_ref","live_birth_recat")])


# List of PFAS
PFAS <- spresto[,c('PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num' )]

# List of covariates
KV_name <- c("Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
             "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
             "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1")

# Name of the outcome - this is where you change the outcome name
y_name  <- "ttp_pregnant_ref"

# Don't touch this
mix_name_1 <- colnames(PFAS)
X1 = PFAS
data_reg <- list(
  
  N   = nrow(spresto),
  
  C  = length(mix_name_1),
  
  X = cbind(X1),
  
  Dalp = rep(1, length(mix_name_1)),
  
  KV = spresto[,KV_name],
  K   = length(KV_name),
  
  sw = spresto$ipw_sb_nomiss,
  
  y = as.vector(spresto[,y_name])
)


fit <- stan(model_code = model_bwqs_stan_w,
            data = data_reg,
            chains = 2,
            iter = 1e4,
            thin = 3,
            refresh = 0, verbose = F,
            control=list(max_treedepth = 20,
                         adapt_delta = 0.999999999999999))


sum_fit_bwqs_preg_sm <- round(summary(fit,
                                          probs = c(0.025, 0.975))$summary,4)

# extract PFAS mixture variable
estimate<- round(c(exp(sum_fit_bwqs_preg_sm['beta1','mean']), exp(sum_fit_bwqs_preg_sm['beta1','2.5%']), exp(sum_fit_bwqs_preg_sm['beta1','97.5%'])), 3)

estimate

PFAS_name<- c('PFHxS', 'PFHpA', 'PFOS_Total', 'PFOA_Linear', 'PFNA', 'PFDA', 'PFHpS')
weights<- as.numeric(sum_fit_bwqs_preg_sm[c('W[1]','W[2]','W[3]','W[4]','W[5]','W[6]','W[7]'),'mean'])
PFAS_weights<- data.frame(PFAS_name, weights) %>% 
               arrange( desc(weights))
PFAS_weights

```

## Live birth
### Individual PFAS
```{r, message=FALSE,warning=FALSE}

## fit the model
PFAS_lb_adjusted_bm_1_matched_reg2<- glm(live_birth_recat ~ PFHxS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss) 


PFAS_lb_adjusted_bm_2_matched_reg2<- glm(live_birth_recat ~PFHpA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_lb_adjusted_bm_3_matched_reg2<- glm(live_birth_recat ~PFOS_Total_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_lb_adjusted_bm_4_matched_reg2<- glm(live_birth_recat ~PFOA_Linear_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_lb_adjusted_bm_5_matched_reg2<- glm(live_birth_recat ~PFNA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_lb_adjusted_bm_6_matched_reg2<- glm(live_birth_recat ~PFDA_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

PFAS_lb_adjusted_bm_7_matched_reg2<- glm(live_birth_recat ~PFHpS_quar_num+Analysis_Batch_recat+age_at_recruitment+ pcv1_highest_education_completed_recat+ethnicity_specified_recat+pcv1_parity_recat,data=blood, family='binomial',weights = blood$ipw_sb_nomiss)

## extract the information from the model
PFAS_lb_adjusted_bm_1_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_1_matched_reg2, ci_method="wald",vcov = "HC3" ,exponentiate = TRUE
))

PFAS_lb_adjusted_bm_2_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_2_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_lb_adjusted_bm_3_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_3_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_lb_adjusted_bm_4_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_4_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_lb_adjusted_bm_5_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_5_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_lb_adjusted_bm_6_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_6_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))

PFAS_lb_adjusted_bm_7_matched_robust_reg2<- as_tibble(model_parameters(PFAS_lb_adjusted_bm_7_matched_reg2, ci_method="wald", vcov = "HC3",exponentiate = TRUE
))




PFAS_lb_adjusted_bm_matched_robust_reg2_estimate<- rbind(PFAS_lb_adjusted_bm_1_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_2_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_3_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_4_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_5_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_6_matched_robust_reg2[2,2],
                                                    PFAS_lb_adjusted_bm_7_matched_robust_reg2[2,2])

PFAS_lb_adjusted_bm_matched_robust_reg2_sd<-rbind(PFAS_lb_adjusted_bm_1_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_2_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_3_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_4_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_5_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_6_matched_robust_reg2[2,3],
                                                    PFAS_lb_adjusted_bm_7_matched_robust_reg2[2,3])

PFAS_lb_adjusted_bm_matched_robust_reg2_ci_low<-rbind(PFAS_lb_adjusted_bm_1_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_2_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_3_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_4_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_5_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_6_matched_robust_reg2[2,5],
                                                    PFAS_lb_adjusted_bm_7_matched_robust_reg2[2,5])

PFAS_lb_adjusted_bm_matched_robust_reg2_ci_high<-rbind(PFAS_lb_adjusted_bm_1_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_2_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_3_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_4_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_5_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_6_matched_robust_reg2[2,6],
                                                    PFAS_lb_adjusted_bm_7_matched_robust_reg2[2,6])

PFAS_lb_adjusted_bm_matched_robust_reg2_p<-rbind(PFAS_lb_adjusted_bm_1_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_2_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_3_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_4_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_5_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_6_matched_robust_reg2[2,9],
                                                    PFAS_lb_adjusted_bm_7_matched_robust_reg2[2,9])

PFAS_name<- c("PFHxS","PFHpA","PFOS_Total","PFOA_Linear","PFNA","PFDA","PFHpS")

## put all infomation in the table
PFAS_lb_adjusted_bm_matched_robust_reg2<- data.frame(PFAS_name,
           round(PFAS_lb_adjusted_bm_matched_robust_reg2_estimate,3),
           round(PFAS_lb_adjusted_bm_matched_robust_reg2_ci_low,3),
           round(PFAS_lb_adjusted_bm_matched_robust_reg2_ci_high,3),
           round(PFAS_lb_adjusted_bm_matched_robust_reg2_p,4))%>% 
unite(ci,CI_low,CI_high,sep=",")


PFAS_lb_adjusted_bm_matched_robust_reg2_table<- flextable(PFAS_lb_adjusted_bm_matched_robust_reg2)%>% 
                 set_header_labels(Coefficient="OR",ci="95% CI",p="p.value") %>% 
                 add_footer_lines(values=c("p.value less than 0.05 is marked in red","Adjusted model: adjusted for Batch effect, age at recruitment, Highest education status, ethinicity, and parity at pcv1 visit"))%>% 
                 color( ~p<0.05,~p,color="red") %>% 
                 theme_box 


PFAS_lb_adjusted_bm_matched_robust_reg2_table

```

### Joint effect of PFAS - BWQS
```{r, message=FALSE,warning=FALSE}

###############################
#BWQS logit regression with IPW
###############################

model_bwqs_stan_w = "data {

int<lower=0> N;          // number of individual
int<lower=0> C;          // number of chemicals
int<lower=0> K;          // number of covariates
matrix[N,C] X;                         // matrix of indipendent variable
matrix[N,K] KV;                       // matrix of covariates
vector[C] Dalp;          // vector of the Dirichlet coefficients
vector[N] sw;            // IPW type of weights
int<lower=0, upper=1> y[N];  // outcome binomial variable
}
parameters {
real beta0;              // intercepts
real beta1;              // overall effect
vector[K] delta;         // covariates coefficients
simplex[C] W;            // weights for contribution of each exposure in the mixture
}
transformed parameters {
vector[N] Xb;
Xb = beta0 + beta1*(X*W) + KV*delta;
}
model {
beta0 ~ normal(0, 100);
beta1 ~ normal(0, 100);
delta ~ normal(0, 100);
W ~ dirichlet(Dalp);
for(n in 1:N){
 target += bernoulli_logit_lpmf(y[n] | Xb[n]) * sw[n];
}


}
generated quantities {
vector[N] log_lik;
for (nn in 1:N)
log_lik[nn] = bernoulli_logit_lpmf(y[nn] | Xb[nn]);
}
"


# Read the data
spresto<- blood %>% 
  select(ttp_pregnant_ref,live_birth_recat,PFHxS_quar_num,PFHpA_quar_num,PFOS_Total_quar_num,PFOA_Linear_quar_num,PFNA_quar_num,PFDA_quar_num,PFHpS_quar_num,Analysis_Batch_recat,age_at_recruitment, pcv1_highest_education_completed_recat,ethnicity_specified_recat,pcv1_parity_recat, ipw_sb_nomiss)

spresto <- na.omit(spresto)
spresto <- DataExplorer::dummify(spresto)

# subset the data
spresto <- as.data.frame(spresto[,c('PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num',
                                    "Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
                                    "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
                                    "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1",
                                   "ipw_sb_nomiss","ttp_pregnant_ref","live_birth_recat")])


# List of PFAS
PFAS <- spresto[,c('PFHxS_quar_num', 'PFHpA_quar_num', 'PFOS_Total_quar_num', 'PFOA_Linear_quar_num', 'PFNA_quar_num', 'PFDA_quar_num', 'PFHpS_quar_num' )]

# List of covariates
KV_name <- c("Analysis_Batch_recat_B2","Analysis_Batch_recat_B3", "Analysis_Batch_recat_B4","Analysis_Batch_recat_B5","age_at_recruitment",
             "pcv1_highest_education_completed_recat_Primary.Secondary.Post_secondary",
             "ethnicity_specified_recat_Chinese", "ethnicity_specified_recat_Indian","pcv1_parity_recat_...1")

# Name of the outcome - this is where you change the outcome name
y_name  <- "live_birth_recat"

# Don't touch this
mix_name_1 <- colnames(PFAS)
X1 = PFAS
data_reg <- list(
  
  N   = nrow(spresto),
  
  C  = length(mix_name_1),
  
  X = cbind(X1),
  
  Dalp = rep(1, length(mix_name_1)),
  
  KV = spresto[,KV_name],
  K   = length(KV_name),
  
  sw = spresto$ipw_sb_nomiss,
  
  y = as.vector(spresto[,y_name])
)


fit <- stan(model_code = model_bwqs_stan_w,
            data = data_reg,
            chains = 2,
            iter = 1e4,
            thin = 3,
            refresh = 0, verbose = F,
            control=list(max_treedepth = 20,
                         adapt_delta = 0.999999999999999))


sum_fit_bwqs_preg_sm <- round(summary(fit,
                                          probs = c(0.025, 0.975))$summary,4)

# extract PFAS mixture variable
estimate<- round(c(exp(sum_fit_bwqs_preg_sm['beta1','mean']), exp(sum_fit_bwqs_preg_sm['beta1','2.5%']), exp(sum_fit_bwqs_preg_sm['beta1','97.5%'])), 3)

estimate

PFAS_name<- c('PFHxS', 'PFHpA', 'PFOS_Total', 'PFOA_Linear', 'PFNA', 'PFDA', 'PFHpS')
weights<- as.numeric(sum_fit_bwqs_preg_sm[c('W[1]','W[2]','W[3]','W[4]','W[5]','W[6]','W[7]'),'mean'])
PFAS_weights<- data.frame(PFAS_name, weights) %>% 
               arrange( desc(weights))
PFAS_weights

```
 

# Figure 1
```{r, message=FALSE,warning=FALSE}

### Create a figure showing the weights from the BWQS models ###
y <- c(0.1791, 0.1608, 0.1321, 0.1725, 0.1248, 0.1154, 0.1153, NA, NA, NA, NA, 0.2439, 0.1533, 0.1552, 0.1269, 0.1032, 0.1032, 0.1142, NA, NA, NA, NA, 0.2077, 0.1607, 0.1516, 0.1372, 0.1112, 0.1099, 0.1218)
cols <- c("brown", "green", "purple", "blue", "red", "orange", "gray", NA, NA, NA, NA, "brown", "green", "purple", "blue", "red", "orange", "gray", NA, NA, NA, NA, "brown", "green", "purple", "blue", "red", "orange", "gray")

### Generate the plot ###
par(mar=c(5, 5, 4, 2) + 0.1)
barplot(y, col=cols, xlim=c(0,33), ylim=c(0,0.5), axes=FALSE, xlab="", ylab="")
axis(2, at=c(0, 0.25, 0.5, 0.75, 1), font=2, cex.axis=1.25, las=1, lwd=3, lwd.ticks=3)
axis(1, at=c(4, 17.4, 30.9), labels=c("TTP", "Pregnant", "Live Birth"), font=2, cex.axis=1.25, las=1, lwd=3, lwd.ticks=3, tick=FALSE, line=-0.5)
mtext("Weight", 2, line=3.45, cex=1.5, font=2)
legend("topleft", x.intersp=0.5, text.font=2, legend=c("PFDA", "PFOS", "PFOA", "PFHpA", "PFHxS", "PFNA", "PFHpS"), fill=c("brown", "green", "purple", "blue", "red", "orange", "gray"))

dev.off()




```





